#!/bin/bash
#
# aja jargi tervitamine
#
echo -n "Sisesta aja vaartus: "
read aeg
# kontrollime
if [ $aeg -ge 22 -a $aeg -lt 24 ] || [ $aeg -ge 0 -a $aeg -lt 6 ];
then
	echo "Head ood!"
fi
# skripti lopp
