#!/bin/bash
#
# Kas antud arv on paaris või paaritu
#
# skripti algus
#
# arvude sisestamine
echo -n "Sisesta suvaline taisarv: "
read arv
#
if [$arv -eq 3]
then
   echo  "$Antud arv on paaritu"
#
if [$arv -eq 8]
then
   echo "$Antud arv on paaris"
#
fi
# 
# skripti lopp


