#!/bin/bash
#
# Kas antud arv on paaris või paaritu
#
# skripti algus
#
# arvude sisestamine
echo -n "Sisesta suvaline taisarv: "
read arv
#
if [$arv -eq paaritu]
then
   echo  "$arv % 2 => 1"
#
# Antud arv on paaritu
if [$arv -eq paaris]
then
   echo "$arv % 2 => 0"
#
# Antud arv on paaris
fi
#
# Arvude vordlemise lopp
# skripti lopp


