#!/bin/bash
#
# Arvude vordlemine(paaris voi paaritu)
#
# skripti algus
#
# arvude sisestamine
echo -n "Sisesta suvaline taisarv: "
read arv
# arvutame jaak 2-ga jagamisel
jaak=$(($arv % ))
# 3 % 2 => 1 -> siis on antud  arv paaritu
# 8 % 2 => 0 -> siis on antud  arv paaris
if [$jaak -eq 1]
then
   echo "$arv on paaritu"
else
    echo "$arv on paaris"
fi
# tingimuse kontroll on loppenud
#
# skripti lopp


