#!/bin/bash
#
# reisi korraldamine
#
# skripti algus
#
echo -n "Sisesta reisijate arv: "
read reisijad
# kohtade andmed bussis
echo -n "Sisesta kohtade arv bussis: "
read kohad
#
# arvutused
#
# jagame inimesed busside vahel nii, et koik kohad bussides oleks taidetud - sellega
# saame teada, palju bussi on vaja
bussid=$(($reisijad / $kohad))
# vaatame, palju on neid, kes ei saanud koha bussides - neid on yle jaanud reisijad, 
# ehk jaagid, kui koik kohad on taidetud
ylejaanud=$(($reisijad % $kohad))
# kui on olemas ylejaanud, tuleb suurendada busside arv 1 vorra
if test $ylejaanud -gt 0
then
	# bussid muutuja vajab yledefineerimist, selle parast ymbersalvestamiseks
	# ei kasuta $ marki, aga arvutamisel juba kasutame
	bussid=$(($bussid + 1))
fi
# tulemuste valjastamine
#
echo "Kokku on vaja $bussid taisbussi"
#
# skripti lopp
