#!/bin/bash
#
# Bussi ekskursioonide korraldamise info
#
# Skripti algus
#
echo -n "Grupis on reisijaid:"
read reisijate arv grupis on 25 inimest
echo "Bussis on kohti $kokku 30, tühjaks jäi $neist 5";
read bussist jäi maha 5 inimest
echo
#
# skripti lopp




